name: Build and upload static site

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - run: tar -czvf dist.tar.gz dist

      - uses: diamondburned/action-upload-release@main
        with:
          files: dist.tar.gz
